export enum AlertType {
  STOCKOUT = 'STOCKOUT',
  ADS_WASTE = 'ADS_WASTE',
  COMPETITOR_PRICE_DROP = 'COMPETITOR_PRICE_DROP',
  RANK_CHANGE = 'RANK_CHANGE',
  REVIEW_ANOMALY = 'REVIEW_ANOMALY',
  SLOW_MOVING = 'SLOW_MOVING',
  ACOS_ANOMALY = 'ACOS_ANOMALY',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  CLOSED = 'CLOSED',
}

export enum ActionType {
  ADJUST_PRICE = 'ADJUST_PRICE',
  PAUSE_ADGROUP = 'PAUSE_ADGROUP',
  ADD_NEGATIVE_KEYWORD = 'ADD_NEGATIVE_KEYWORD',
  ADJUST_BUDGET = 'ADJUST_BUDGET',
  ADJUST_BID = 'ADJUST_BID',
  CREATE_REORDER = 'CREATE_REORDER',
  EXPAND_KEYWORDS = 'EXPAND_KEYWORDS',
  CHANGE_MATCH_TYPE = 'CHANGE_MATCH_TYPE',
}

export enum ActionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
  EXECUTED_FAILED = 'EXECUTED_FAILED',
  VERIFIED = 'VERIFIED',
  ROLLED_BACK = 'ROLLED_BACK',
  CLOSED = 'CLOSED',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RecommendationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  OPERATOR = 'OPERATOR',
  VIEWER = 'VIEWER',
}

export enum StoreStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum SkuStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DISCONTINUED = 'DISCONTINUED',
  TESTING = 'TESTING',
}

export enum MetricWindow {
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}
