-- 迁移004：SKU成本结构增强
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS purchase_price DECIMAL(12,2);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(12,2);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS packaging_cost DECIMAL(12,2);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS exchange_rate DECIMAL(10,4);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS weight DECIMAL(8,2);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS box_size VARCHAR(100);
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS pack_per_box INT;
ALTER TABLE sku_master ADD COLUMN IF NOT EXISTS promoter VARCHAR(100);
