-- 迁移006：广告数据增强字段
ALTER TABLE ads_facts ADD COLUMN IF NOT EXISTS ctr DECIMAL(8,4) NOT NULL DEFAULT 0;
ALTER TABLE ads_facts ADD COLUMN IF NOT EXISTS conversion_rate DECIMAL(8,4) NOT NULL DEFAULT 0;
ALTER TABLE ads_facts ADD COLUMN IF NOT EXISTS cost_per_conversion DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE ads_facts ADD COLUMN IF NOT EXISTS direct_sales DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE ads_facts ADD COLUMN IF NOT EXISTS direct_orders INT NOT NULL DEFAULT 0;
